### ISSUE TITLE
session_expired? 

### ISSUE THREAD

**Issue by gyruskaz** [twilio-samples/speech-assistant-openai-realtime-api-python#10]
`{"type": "error", "event_id": "event_AGvaHyTGxxeq2s6GtXhVY", "error": {"type": "invalid_request_error", "code": "session_expired", "message": "Your session hit the maximum duration of 15 minutes.", "param": null, "event_id": null}}
`

i get this once every minute or so after leaving main.py running for 15 minutes, doesn't matter if websocket connection is open or closed. Not sure if there's an easy fix or if it's something to be concerned about. I can still make calls to the assistant while continuing to get the error periodically.

![Screenshot_20241010_161532](https://github.com/user-attachments/assets/45c15fdc-65c1-483b-a2ea-60fa12f36f74)

**Comment by pkamp3** [comment]
I'm not sure of OpenAI's session plans. 15 minute sessions was their limit at launch. I think you can follow this link to see if and when it changes: https://platform.openai.com/docs/guides/realtime/handling-long-conversations

**Comment by gyruskaz** [comment]
It's not that I want to have conversations longer than 15 minutes. It's that when I hang up the call, it still thinks the openai_ws is open and I'm not sure why. I would think that 

`            except WebSocketDisconnect:
                print("Client disconnected.")
                if openai_ws.open:
                    await openai_ws.close()`
                    
would take care of it ....
