### ISSUE TITLE
Running this on production?

### ISSUE THREAD

**Issue by dbee01** [twilio-samples/speech-assistant-openai-realtime-api-python#12]
I don't need the ngrok port forwarding. I'm trying to roll it out to live but I seem to be having issues with OpenAI connecting to the media-stream websocket. 

`INFO:     Started server process [8276]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:5050 (Press CTRL+C to quit)
here
<?xml version="1.0" encoding="UTF-8"?><Response><Say>Please wait while we connect your call to the A. I. voice assistant, powered by Twilio and the Open-A.I. Realtime API</Say><Pause length="1" /><Say>O.K. you can start talking!</Say><Connect><Stream url="wss://45.133.178.13/media-stream" /></Connect></Response>
INFO:     34.255.178.120:35938 - "POST /incoming-call HTTP/1.1" 200 OK
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.`

how do i set this up so that OpenAI can connect to the media-stream websocket over SSL presumably? I'm running nginx on a VPS.

So far i've opened the firewall ports, i've tried everything i can think of in the nginx default file. The call hangs up immediately after the "O.K. you can start talking!" response?

**Comment by dbee01** [comment]
`wscat -c wss://45.133.178.13:5050/media-stream
error: write EPROTO 40E8236E037A0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:`

i can't connect to this websocket :-(

**Comment by bnb** [comment]
Hey! This is out of the scope of this repo and the work we do in it. Might want to ask the same on StackOverflow 😊
