### ISSUE TITLE
I don't understand this line from the latest PR and it gives me errors locally

### ISSUE THREAD

**Issue by frmsaul** [twilio-samples/speech-assistant-openai-realtime-api-python#17]
[The PR](https://github.com/twilio-samples/speech-assistant-openai-realtime-api-python/pull/13)

```
    await openai_ws.send(json.dumps(initial_conversation_item))
    await openai_ws.send(json.dumps({"type": "response.create"})) # <- This line
```

https://github.com/twilio-samples/speech-assistant-openai-realtime-api-python/commit/5ecab73eb4b955acbd86b94dcc440ecab0df51d2#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1R202

Anyone understand why it's there and what goal it accomplishes? Removing it makes things work for me.

**Comment by frmsaul** [comment]
It also seems that `mark_queue` doesn't do anything. I'm struggling to understand why it was added in this PR.

**Comment by pkamp3** [comment]
@frmsaul what error are you seeing locally? When you remove it, can you still get the AI to talk first?

[OpenAI's docs say to use `response.create`](https://platform.openai.com/docs/api-reference/realtime-client-events/response/create) if `server_vad` isn't triggering model inference. We use `server_vad`, but only after the caller starts talking.

I fill up `mark_queue` as [OpenAI sends `response.audio.delta`](https://platform.openai.com/docs/api-reference/realtime-server-events/response/audio/delta), then `pop` from it as each mark is hit. When it's empty, I know Twilio played the whole  response to the user. Then, I don't need to trigger the interrupt logic unnecessarily on [`input_audio_buffer.speech_started`](https://platform.openai.com/docs/api-reference/realtime-server-events/input_audio_buffer/speech_started).

**Comment by Manuteaa** [comment]
@pkamp3 Perhaps you could just send a single mark, when we receive the OpenAI 'done' event, then use the mark Twilio response to know when Twilio has played the entire response ? I encountered strange audio delays with a mark for each answer audio chunk, but switching to a single mark resolved the issue.
