### ISSUE TITLE
[Enhancement] Mark events

### ISSUE THREAD

**Issue by Manuteaa** [twilio-samples/speech-assistant-openai-realtime-api-python#20]
@pkamp3 Perhaps you could just send a single mark, when we receive the OpenAI `response.done` event, then use the mark Twilio response to know when Twilio has played the entire response ? I encountered strange audio delays with a mark for each answer audio chunk, but switching to a single mark resolved the issue.

**Comment by pkamp3** [comment]
@Manuteaa I haven't been able to reproduce this, but I'll note that one of my colleagues internally had a successful implementation with counting mark messages (just an integer counter, where 0 would be the same as our empty queue here) instead of managing the queue.
