### ISSUE TITLE
interruption handling in the latest commit

### ISSUE THREAD

**Issue by gyruskaz** [twilio-samples/speech-assistant-openai-realtime-api-python#22]
I get the following error occasionally: 
{'type': 'error', 'event_id': 'event_AOTheE0Xl3nJeu2iVnVeI', 'error': {'type': 'invalid_request_error', 'code': None, 'message': 'Audio content of 13600ms is already shorter than 55960ms', 'param': None, 'event_id': None}}

**Comment by pkamp3** [comment]
@gyruskaz are there any other symptoms from this error? It seems like the Mark Queue isn't emptying properly and you/we sent an interruption when it wasn't needed.
