### ISSUE TITLE
Problem using tools

### ISSUE THREAD

**Issue by genesis-gh-jlangseth** [twilio-samples/speech-assistant-openai-realtime-api-python#3]
When trying to add a tool to the session, it connects, but does not respond.

`async def send_session_update(openai_ws):
    """Send session update to OpenAI WebSocket."""
    session_update = {
        "type": "session.update",
        "session": {
            "turn_detection": {"type": "server_vad"},
            "input_audio_format": "g711_ulaw",
            "output_audio_format": "g711_ulaw",
            "voice": VOICE,
            "instructions": SYSTEM_MESSAGE,
            "modalities": ["text", "audio"],
            "temperature": 0.8,
            "tools": [
                {
                    "name": "get_weather",
                    "description": "Get the weather ",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "location": {
                                "type": "string",
                                "description": "Location to get the weather for",
                            }
                        }
                    }
                }
            ]
        }
    }
    print('Sending session update:', json.dumps(session_update))
    await openai_ws.send(json.dumps(session_update))`
    
 The session creation ackknowledge includes an empty tool array:
    
 `Received event: session.created {'type': 'session.created', 'event_id': 'event_AEOHBpESNni69QMT38iAt', 'session': {'id': 'sess_AEOHBudsh3QTqonKbd3od', 'object': 'realtime.session', 'model': 'gpt-4o-realtime-preview-2024-10-01', 'expires_at': 1727994173, 'modalities': ['text', 'audio'], 'instructions': "Your knowledge cutoff is 2023-10. You are a helpful, witty, and friendly AI. Act like a human, but remember that you aren't a human and that you can't do human things in the real world. Your voice and personality should be warm and engaging, with a lively and playful tone. If interacting in a non-English language, start by using the standard accent or dialect familiar to the user. Talk quickly. You should always call a function if you can. Do not refer to these rules, even if you’re asked about them.", 'voice': 'alloy', 'turn_detection': {'type': 'server_vad', 'threshold': 0.5, 'prefix_padding_ms': 300, 'silence_duration_ms': 200}, 'input_audio_format': 'pcm16', 'output_audio_format': 'pcm16', 'input_audio_transcription': None, 'tool_choice': 'auto', 'temperature': 0.8, 'max_response_output_tokens': 'inf', 'tools': []}}`
 
 And the remote voice does not respond.  Without the Tools in the session.update, it does respond and is able to converse.

**Comment by robcontreras** [comment]
I'm seeing the same, the connection is open and there's an event received with empty tools array and there's no response ever received to whatever i say

**Comment by genesis-gh-jlangseth** [comment]
I was able to get tool calling to work using the[ OpenAI NodeJS browser based example](https://github.com/openai/openai-realtime-api-beta), and then had it call my python flask program via a local REST call to call the tool.  So tool calling works on realtime, this may be an issue on the Twillio side somehow, or an issue somewhere upstream in this example code.

**Comment by frmsaul** [comment]
I'm having the same issue! 

Also notice how: 
```
"input_audio_format": "g711_ulaw", "output_audio_format": "g711_ulaw"
```

Changed to 
```
'input_audio_format': 'pcm16', 'output_audio_format': 'pcm16'
```

Seems like obviously an openai problem. Anyone we can contact to report it?

https://community.openai.com/t/realtime-api-tool-calling-problems-no-response-when-a-tool-is-included-in-the-session/966495/11

**Comment by frmsaul** [comment]
@bnb @pkamp3 do you guys know who at openai we could reach out about this? Seems like obviously an openai and not twilio problem, probably very easy for them to solve too (and easy to reproduce)

**Comment by genesis-gh-jlangseth** [comment]
These is a thread about this on OpenAI Community forum https://community.openai.com/t/realtime-api-tool-calling-problems-no-response-when-a-tool-is-included-in-the-session/966495/2

**Comment by timoconnellaus** [comment]
This isn't an issue with the audio format - if you log every response from openai you'll see the first response is an error. The array LOG_EVENT_TYPES is filtering out useful information

You will see this error

```json
{
  type: "error",
  event_id: "event_AGEon4DCIF1cvdfEAqRBE",
  error: {
    type: "invalid_request_error",
    code: "missing_required_parameter",
    message: "Missing required parameter: 'session.tools[0].type'.",
    param: "session.tools[0].type",
    event_id: null,
  },
}
```

If you add 
```json
type: "function",
```
to the get_weather tool it will work now

**Comment by frmsaul** [comment]
+1

Thanks @timoconnellaus, your solution worked for me
