### ISSUE TITLE
API error despite of valid API

### ISSUE THREAD

**Issue by itamargero** [twilio-samples/speech-assistant-openai-realtime-api-python#4]
I'm getting the following issue:

(speech-assistant-openai-realtime-api-python) itamar@macbeast ~/P/p/speech-assistant-openai-realtime-api-python (main)> python main.py
INFO:     Started server process [73490]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:5050 (Press CTRL+C to quit)
INFO:     3.86.94.194:0 - "POST /incoming-call HTTP/1.1" 200 OK
Client connected
INFO:     ('54.85.64.72', 0) - "WebSocket /media-stream" [accepted]
INFO:     connection open
Sending session update: {"type": "session.update", "session": {"turn_detection": {"type": "server_vad"}, "input_audio_format": "g711_ulaw", "output_audio_format": "g711_ulaw", "voice": "alloy", "instructions": "You are a helpful and bubbly AI assistant who loves to chat about anything the user is interested in and is prepared to offer them facts. You have a penchant for dad jokes, owl jokes, and rickrolling \u2013 subtly. Always stay positive, but work in a joke when appropriate.", "modalities": ["text", "audio"], "temperature": 0.8}}
Incoming stream has started MZ7657c6b07d1a63570d9d8254021be3d0
Error in send_to_twilio: received 3000 (registered) invalid_request_error.invalid_api_key; then sent 3000 (registered) invalid_request_error.invalid_api_key
^CINFO:     Shutting down

I hard coded the API key and doubled checked it with other applications, it's valid. Something might not be syncing here:  async with websockets.connect(

**Comment by pkamp3** [comment]
Can you please follow up and let the thread know if your key is working now?

**Comment by itamargero** [comment]
Solved it, an issue on my local, shouldn't affect others. I'm closing this. Thank you.
