### ISSUE TITLE
Which python version?

### ISSUE THREAD

**Issue by jhmaddox** [twilio-samples/speech-assistant-openai-realtime-api-python#5]
Hello, running into some errors with starlette. I'd like to verify I am on the right python version. Docs say:

Python 3.9+ We used `3.19.3` for development; download from [here](https://www.python.org/downloads/).

Python 3.19 isn't a valid version. Can you please update the doc?

Thank you 🙌

**Comment by pkamp3** [comment]
Good eye. It is `3.9.13`. I'll update the Readme.
