### ISSUE TITLE
OpenAI API Rate Limits Hit Too Soon

### ISSUE THREAD

**Issue by needsmorejpeg** [twilio-samples/speech-assistant-openai-realtime-api-python#7]
Hi team, thank you for putting together this example!

I've enjoyed playing around with the AI assistant over the phone, it feels more "real" than the OpenAI playground! However, I keep running into rate limit issues with the phone use case -- and I don't get rate limited on the OpenAI playground under the same account.

Have you experienced any similar issues? I wonder if I'm being billed for all the input while the AI is speaking, or something along those lines? My calls seem to get cut off after a minute or two when using this code, but I can go on indefinitely in the playground. I'm only running one call at a time, and my rate limit is 20k TPM, which should be more than sufficient.

**Comment by bnb** [comment]
Hey! We can't really help with differences between the playground in comparison to tokens that you individually have. Might be a good question for StackOverflow or a Discord community for programming in your language of choice.
